# Generated by Django 6.0.5 on 2026-05-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_task_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this client should be treated as active.'),
        ),
    ]
